spring:
  application:
    name: alibaba-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.152.131:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 8082